#pragma once

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define BLYNK_TEMPLATE_ID "YOUR_BLYNK_ID"
#define BLYNK_TEMPLATE_NAME "YOUR_BLYNK_NAME"
#define BLYNK_AUTH_TOKEN "YOUR_BLYNK_TOKEN"

#define TELEGRAM_BOT_TOKEN "YOUR_TELEGRAM_BOT_TOKEN"
#define TELEGRAM_CHAT_ID "YOUR_TELEGRAM_CHAT_ID"

#define FIREBASE_API_KEY "YOUR_FIREBASE_API_KEY"
#define FIREBASE_DB_URL "YOUR_FIREBASE_DATABASE_URL"

#define FIREBASE_DEVICE_EMAIL "YOUR_FIREBASE_DEVICE_EMAIL"
#define FIREBASE_DEVICE_PASSWORD "YOUR_FIREBASE_DEVICE_PASSWORD"
#define FIREBASE_DEVICE_UID "YOUR_FIREBASE_DEVICE_UID"